defmodule Datos do
  def recolectores do
    [
      %{codigo: "R01", nombre: "Luz Marina Ospina", alimentacion: true},
      %{codigo: "R02", nombre: "Jhon Fredy Castaño", alimentacion: false},
      %{codigo: "R03", nombre: "Dora Cardona", alimentacion: true},
      %{codigo: "R04", nombre: "Wilson Arango", alimentacion: false},
      %{codigo: "R05", nombre: "Carlos Alberto Giraldo", alimentacion: true},
      %{codigo: "R06", nombre: "Martha Elena López", alimentacion: true},
      %{codigo: "R07", nombre: "Luis Fernando Ramírez", alimentacion: false},
      %{codigo: "R08", nombre: "Gloria Patricia Gómez", alimentacion: false},
      %{codigo: "R09", nombre: "Héctor Fabio Restrepo", alimentacion: true},
      %{codigo: "R10", nombre: "Sandra Milena Cárdenas", alimentacion: false}
    ]
  end

  def lotes do
    [
      %{id: "L1", nombre: "El Mirador", hectareas: 2.5},
      %{id: "L2", nombre: "La Cañada", hectareas: 1.5},
      %{id: "L3", nombre: "Buenavista", hectareas: 3.0},
      %{id: "L4", nombre: "La Esperanza", hectareas: 2.0}
    ]
  end

  def pesajes do
    [
      %{recolector: "R01", lote: "L1", dia: 1, kilos: 45, verdes: 1},
      %{recolector: "R01", lote: "L2", dia: 1, kilos: 58, verdes: 4},
      %{recolector: "R01", lote: "L3", dia: 2, kilos: 71, verdes: 7},
      %{recolector: "R01", lote: "L4", dia: 2, kilos: 84, verdes: 1},
      %{recolector: "R01", lote: "L1", dia: 3, kilos: 97, verdes: 4},
      %{recolector: "R01", lote: "L2", dia: 4, kilos: 110, verdes: 7},
      %{recolector: "R01", lote: "L3", dia: 5, kilos: 52, verdes: 1},
      %{recolector: "R01", lote: "L4", dia: 6, kilos: 65, verdes: 4},
      %{recolector: "R01", lote: "L1", dia: 6, kilos: 78, verdes: 7},
      %{recolector: "R02", lote: "L2", dia: 1, kilos: 62, verdes: 3},
      %{recolector: "R02", lote: "L3", dia: 1, kilos: 75, verdes: 6},
      %{recolector: "R02", lote: "L4", dia: 2, kilos: 88, verdes: 9},
      %{recolector: "R02", lote: "L1", dia: 2, kilos: 101, verdes: 3},
      %{recolector: "R02", lote: "L2", dia: 3, kilos: 114, verdes: 6},
      %{recolector: "R02", lote: "L3", dia: 4, kilos: 56, verdes: 9},
      %{recolector: "R02", lote: "L4", dia: 5, kilos: 69, verdes: 3},
      %{recolector: "R02", lote: "L1", dia: 6, kilos: 82, verdes: 6},
      %{recolector: "R02", lote: "L2", dia: 6, kilos: 95, verdes: 9},
      %{recolector: "R03", lote: "L3", dia: 1, kilos: 79, verdes: 5},
      %{recolector: "R03", lote: "L4", dia: 1, kilos: 92, verdes: 8},
      %{recolector: "R03", lote: "L1", dia: 2, kilos: 105, verdes: 2},
      %{recolector: "R03", lote: "L2", dia: 2, kilos: 47, verdes: 5},
      %{recolector: "R03", lote: "L3", dia: 3, kilos: 60, verdes: 8},
      %{recolector: "R03", lote: "L4", dia: 4, kilos: 73, verdes: 2},
      %{recolector: "R03", lote: "L1", dia: 5, kilos: 86, verdes: 5},
      %{recolector: "R03", lote: "L2", dia: 6, kilos: 99, verdes: 8},
      %{recolector: "R03", lote: "L3", dia: 6, kilos: 112, verdes: 2},
      %{recolector: "R04", lote: "L4", dia: 1, kilos: 96, verdes: 7},
      %{recolector: "R04", lote: "L1", dia: 1, kilos: 109, verdes: 1},
      %{recolector: "R04", lote: "L2", dia: 2, kilos: 51, verdes: 4},
      %{recolector: "R04", lote: "L3", dia: 2, kilos: 64, verdes: 7},
      %{recolector: "R04", lote: "L4", dia: 3, kilos: 77, verdes: 1},
      %{recolector: "R04", lote: "L1", dia: 4, kilos: 90, verdes: 4},
      %{recolector: "R04", lote: "L2", dia: 5, kilos: 103, verdes: 7},
      %{recolector: "R04", lote: "L3", dia: 6, kilos: 45, verdes: 1},
      %{recolector: "R04", lote: "L4", dia: 6, kilos: 58, verdes: 4},
      %{recolector: "R05", lote: "L1", dia: 1, kilos: 113, verdes: 9},
      %{recolector: "R05", lote: "L2", dia: 1, kilos: 55, verdes: 3},
      %{recolector: "R05", lote: "L3", dia: 2, kilos: 68, verdes: 6},
      %{recolector: "R05", lote: "L4", dia: 2, kilos: 81, verdes: 9},
      %{recolector: "R05", lote: "L1", dia: 3, kilos: 94, verdes: 3},
      %{recolector: "R05", lote: "L2", dia: 4, kilos: 107, verdes: 6},
      %{recolector: "R05", lote: "L3", dia: 5, kilos: 49, verdes: 9},
      %{recolector: "R05", lote: "L4", dia: 6, kilos: 62, verdes: 3},
      %{recolector: "R05", lote: "L1", dia: 6, kilos: 75, verdes: 6},
      %{recolector: "R06", lote: "L2", dia: 1, kilos: 59, verdes: 2},
      %{recolector: "R06", lote: "L3", dia: 1, kilos: 72, verdes: 5},
      %{recolector: "R06", lote: "L4", dia: 2, kilos: 85, verdes: 8},
      %{recolector: "R06", lote: "L1", dia: 2, kilos: 98, verdes: 2},
      %{recolector: "R06", lote: "L2", dia: 3, kilos: 111, verdes: 5},
      %{recolector: "R06", lote: "L3", dia: 4, kilos: 53, verdes: 8},
      %{recolector: "R06", lote: "L4", dia: 5, kilos: 66, verdes: 2},
      %{recolector: "R06", lote: "L1", dia: 6, kilos: 79, verdes: 5},
      %{recolector: "R06", lote: "L2", dia: 6, kilos: 92, verdes: 8},
      %{recolector: "R07", lote: "L3", dia: 1, kilos: 76, verdes: 4},
      %{recolector: "R07", lote: "L4", dia: 1, kilos: 89, verdes: 7},
      %{recolector: "R07", lote: "L1", dia: 2, kilos: 102, verdes: 1},
      %{recolector: "R07", lote: "L2", dia: 2, kilos: 115, verdes: 4},
      %{recolector: "R07", lote: "L3", dia: 3, kilos: 57, verdes: 7},
      %{recolector: "R07", lote: "L4", dia: 4, kilos: 70, verdes: 1},
      %{recolector: "R07", lote: "L1", dia: 5, kilos: 83, verdes: 4},
      %{recolector: "R07", lote: "L2", dia: 6, kilos: 96, verdes: 7},
      %{recolector: "R07", lote: "L3", dia: 6, kilos: 109, verdes: 1},
      %{recolector: "R08", lote: "L4", dia: 1, kilos: 93, verdes: 6},
      %{recolector: "R08", lote: "L1", dia: 1, kilos: 106, verdes: 9},
      %{recolector: "R08", lote: "L2", dia: 2, kilos: 48, verdes: 3},
      %{recolector: "R08", lote: "L3", dia: 2, kilos: 61, verdes: 6},
      %{recolector: "R08", lote: "L4", dia: 3, kilos: 74, verdes: 9},
      %{recolector: "R08", lote: "L1", dia: 4, kilos: 87, verdes: 3},
      %{recolector: "R08", lote: "L2", dia: 5, kilos: 100, verdes: 6},
      %{recolector: "R08", lote: "L3", dia: 6, kilos: 113, verdes: 9},
      %{recolector: "R08", lote: "L4", dia: 6, kilos: 55, verdes: 3},
      %{recolector: "R09", lote: "L1", dia: 1, kilos: 110, verdes: 8},
      %{recolector: "R09", lote: "L2", dia: 1, kilos: 52, verdes: 2},
      %{recolector: "R09", lote: "L3", dia: 2, kilos: 65, verdes: 5},
      %{recolector: "R09", lote: "L4", dia: 2, kilos: 78, verdes: 8},
      %{recolector: "R09", lote: "L1", dia: 3, kilos: 91, verdes: 2},
      %{recolector: "R09", lote: "L2", dia: 4, kilos: 104, verdes: 5},
      %{recolector: "R09", lote: "L3", dia: 5, kilos: 46, verdes: 8},
      %{recolector: "R09", lote: "L4", dia: 6, kilos: 59, verdes: 2},
      %{recolector: "R09", lote: "L1", dia: 6, kilos: 72, verdes: 5},
      %{recolector: "R10", lote: "L2", dia: 1, kilos: 56, verdes: 1},
      %{recolector: "R10", lote: "L3", dia: 1, kilos: 69, verdes: 4},
      %{recolector: "R10", lote: "L4", dia: 2, kilos: 82, verdes: 7},
      %{recolector: "R10", lote: "L1", dia: 2, kilos: 95, verdes: 1},
      %{recolector: "R10", lote: "L2", dia: 3, kilos: 108, verdes: 4},
      %{recolector: "R10", lote: "L3", dia: 4, kilos: 50, verdes: 7},
      %{recolector: "R10", lote: "L4", dia: 5, kilos: 63, verdes: 1},
      %{recolector: "R10", lote: "L1", dia: 6, kilos: 76, verdes: 4},
      %{recolector: "R10", lote: "L2", dia: 6, kilos: 89, verdes: 7},
      %{recolector: "R99", lote: "L1", dia: 1, kilos: 80, verdes: 3},
      %{recolector: "R98", lote: "L2", dia: 2, kilos: 60, verdes: 4},
      %{recolector: "R01", lote: "L9", dia: 2, kilos: 70, verdes: 3},
      %{recolector: "R02", lote: "L8", dia: 4, kilos: 55, verdes: 2},
      %{recolector: "R03", lote: "L1", dia: 7, kilos: 80, verdes: 3},
      %{recolector: "R04", lote: "L2", dia: 0, kilos: 70, verdes: 4},
      %{recolector: "R05", lote: "L3", dia: 3, kilos: 0, verdes: 2},
      %{recolector: "R06", lote: "L4", dia: 5, kilos: 251, verdes: 3},
      %{recolector: "R07", lote: "L1", dia: 2, kilos: 90, verdes: 101},
      %{recolector: "R08", lote: "L2", dia: 6, kilos: 75, verdes: -1},
    ]
  end
end
